//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sb_admin_2.Web.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Category
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Category()
        {
            this.Contributions = new HashSet<Contribution>();
        }

        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public System.Guid CategoryID { get; set; }
        public string CategoryName { get; set; }
        public Nullable<System.DateTime> ClosureDate { get; set; }
        public Nullable<System.DateTime> FinalClosureDate { get; set; }
        public Nullable<System.Guid> Faculty_DetailID { get; set; }
        public string Description { get; set; }
        public Nullable<int> Status { get; set; }
    
        public virtual Faculty_Detail Faculty_Detail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contribution> Contributions { get; set; }
    }
}
