//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sb_admin_2.Web.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Comment
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public System.Guid CommentID { get; set; }
        public string Content { get; set; }
        public Nullable<System.Guid> Creator { get; set; }
        public Nullable<System.Guid> Contribution { get; set; }
        public Nullable<System.DateTime> CommentDate { get; set; }
        public Nullable<int> Status { get; set; }
    
        public virtual Contribution Contribution1 { get; set; }
        public virtual User User { get; set; }
    }
}
