//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sb_admin_2.Web.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Document
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public System.Guid DocumentID { get; set; }
        public string DocumentName { get; set; }
        public string Path { get; set; }
        public Nullable<System.DateTime> UploadDate { get; set; }
        public Nullable<System.Guid> Contribution { get; set; }
    
        public virtual Contribution Contribution1 { get; set; }
    }
}
